---
http_interactions:
- request:
    method: get
    uri: http://<%= username %>:<%= password %>@localhost:8080/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Connection:
      - keep-alive
      Www-Authenticate:
      - Basic realm="ApplicationRealm"
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - text/html;charset=UTF-8
      Content-Length:
      - '71'
      Date:
      - Wed, 12 Apr 2017 15:07:45 GMT
    body:
      encoding: UTF-8
      string: "<html><head><title>Error</title></head><body>Unauthorized</body></html>"
    http_version: 
  recorded_at: Wed, 12 Apr 2017 15:07:45 GMT
recorded_with: VCR 3.0.3
