hawkular:
  # TODO: put this back to hawkular/hawkular-services:latest once everything is merged in the h-services and the docker image is released
  image: "jotak/hawkular-services:latest"
  ports:
    - "8080:8080"
    - "8443:8443"
    - "9990:9990"
  links:
    - myCassandra
  volumes:
    - /tmp/opt/hawkular/server:/opt/data
  environment:
    - CASSANDRA_NODES=myCassandra
    - ADMIN_TOKEN
myCassandra:
  image: cassandra:3.0.9
  environment:
    - CASSANDRA_START_RPC=true
