hawkular:
  image: "jotak/hawkular-services:latest"
  ports:
    - "8080:8080"
    - "8443:8443"
    - "9990:9990"
  links:
    - myCassandra
  volumes:
    - /home/jotak/hservices/opt/data:/opt/data:Z
  environment:
    - CASSANDRA_NODES=myCassandra
    - ADMIN_TOKEN
myCassandra:
  image: cassandra:3.0.9
  environment:
    - CASSANDRA_START_RPC=true
