---
http_interactions:
- request:
    method: get
    uri: https://jdoe:password@hawkular.torii.gva.redhat.com/hawkular/inventory/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
  response:
    status:
      code: 500
      message: Internal Server Error
    headers:
      Server:
      - nginx/1.10.1
      Date:
      - Tue, 21 Mar 2017 18:17:28 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '155'
      Connection:
      - keep-alive
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Pragma:
      - no-cache
    body:
      encoding: UTF-8
      string: |-
        {
          "errorMsg" : "RESTEASY003210: Could not find resource for full path: http://hawkular.torii.gva.redhat.com/hawkular/inventory/hawkular/metrics/status"
        }
    http_version: 
  recorded_at: Tue, 21 Mar 2017 18:17:28 GMT
recorded_with: VCR 3.0.3
