---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:<%= feed_uuid %>,type:rt,id:WildFly%20Server"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '108'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 25 Apr 2017 07:44:58 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '999'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.rt.WildFly Server","data":[{"timestamp":1493106281622,"value":"H4sIAAAAAAAAAO1WUW/TMBD+K5afXYnnvaBBhyhiBTXdEEITcuPrYsmxg33uqKb9d85x26RdthVUCR54SfzdOfc5d98ld8+1XYFF59cF+lhi9MDP7jmuG7pzD8FFX8I8QcGVRJm8jXcNeNQQCD0IrhXt/aKNemfWrAC/Ak+7raxhyO4i3jptbzfP2tLVG0SwrGi7B5toEolE7WxLf/bt/vkDjKExbt0R7/CxhARfotBBLgywHLqmxPXohnyno76wTzIPuU5H/GE866gyOF3wGRgnVRd/h48WSQp/YVHj+mWFNNITDYJPggo7VhuNeY5R8JU0se0Lqcg4ctase12ycM6k7oBQet0kwSbZV4AVeEYXFlrps1C5aBQLKD0ybZmP1hIFq50Cdj6+nEy/f5p+/MruKrBMI6PuS1tDG3spo8HrfA6+lCakhvTwI2oP9G6thU4aA4zK6Ck5OMq0o9LZpb4dOu9RMSmodwYep++w1jfHlDu//JCKB32nVFqINezRZXw6iqKKqNyd7Uh6ln9U0KhroI09deg28ftinuddSbQBSE8qMHRMGuPumCxRr4CR1UKZ9rc+5aW2j0X2alC0G6G/1FJF7p9eRy1g2ySgmFxi22Q55a//jsKLGBqwvS9aZ/ivgKcUcMoCXFl1MAf0LMf3+o34rTLkb2zM40pRVlDLP6nFNJ+4vQn+2TtFIxnbWPeg4NfgQ67NdiX4bPNHuaQ/SvrG9aHgeQJjBUpsldmHYivUzr2HBb+6moxTNtNN8PeupomDilim2ZHsBwbBp+mvtn2h3To9GXBTmd1S8DcuEte5ogIESuwBFnxS1xHTmEO+bk12y946iyQ1mi3P9mEnq6HyDGmr7YAwIcH83NaN1Oh1OT+wP/wC/lm7AjkLAAA="}]}]'
    http_version: 
  recorded_at: Tue, 25 Apr 2017 07:44:58 GMT
recorded_with: VCR 3.0.3
