---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:03eca767\\-e48f\\-4f0b\\-9a8a\\-d8f46112c9a5,type:r,restypes:.*\\|URL\\|.*"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '142'
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 05 Apr 2017 08:03:48 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 05 Apr 2017 08:03:48 GMT
recorded_with: VCR 3.0.3
