---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:<%= feed_uuid %>,type:mt,id:Platform_File%20Store_Total%20Space"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '127'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 12 Apr 2017 08:02:35 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '396'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.mt.Platform_File Store_Total Space","data":[{"timestamp":1491984012613,"value":"H4sIAAAAAAAAAFWPT4vCQAzFv4rk3IPgrbdd/IO3hXYPnmSYxm4gTUrMiCL97s5QFfcU3kvej5c7kFxQXO3WuKXoyRDqO/htzBMGdKPYFlFBFzyU3Wg6ojnhOaupAury5Q8HP6kNxy0xLpoMxGOrHnjRjCGWuIShIP+bmrxXkv5JkqjDWyUhz4HvQ7tp8uncZZ1LtHO5PqS+MKIyY3RS2YujXQJDvVouq9cTu6/f3QYyMP4Rd4ZS8NO8Pu+lwyvUkpirj3c//ekB8Z4mnSUBAAA="}]}]'
    http_version: 
  recorded_at: Wed, 12 Apr 2017 08:02:35 GMT
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:<%= feed_uuid %>,type:r,mtypes:.*\\|Platform_File\\
        Store_Total\\ Space\\|.*"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '140'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 12 Apr 2017 08:02:35 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1639'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.r.platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem","data":[{"timestamp":1491984013251,"value":"H4sIAAAAAAAAAO2bXW/aMBSG/0oUqXedUr6lol50LZ2QxkCEXlQIITdx22iJjYzDhiry22cTIHEwAdp8sJKbpnGMzzkP73Ec5/CuWmgGEcVkrlPiGtQlUL1+V+l8wo4qgVPsEgOql6oJKOBXJgRPIKEWnLKzxaVqmazfxAb0BRPH07q9Vv920P71Y6w/6YNW56YEzeeG8WxUwHNp3GUfBdRCr/p8SqHDhkXA4Yb29MIufcWsYWUSGdjZnK19HDCXe4C+sdE02nwDf367NiDaSzM8tkZos7dyNrBzUb5amWLjGW+WbRKIeLAOpMQy1Ovhe3z8nbbX94aCoQ8iGXmdgbftoeJfHfcINuB0qtxhF9EAX7Q5jpcf02G0nFhaa29Yw9qwgW0bGtTCqI0oJDNgq9fItW2R62JxeSpA/YNy13tUfmJgBki3L2QE1T9wpr1H9ndl/H8Fy91Xbmfs4ivcghu5mDVgbp4dAgcOhTwKZp39c8MH8WoP7Z+tsT7o9ls3mglnmgMmrIf2Ak1MwLc37IR4Plg2VHQ2i0NluKPzKLVplBvndLn5/CfQA7iJyg3YjQeYAlvRJ8AIsRUb09BoGKDvAz9bGTy9xP8M4ccpeOYnIuJIa+qMfXsfgDzazzkdqARjenC6885FugcoinTPi3CR7gdA9XYk9jmmsFckawYsi7Tcha/T6nT7Tzcd6GAyD9BsztPJx9Xw+WeiEL4oH79tfDsDlr3USZSR5EoaEor6wfSzsXeC+bifqD+HRWlGWlMkuZ7UjqaYYhr2+t27lq53+zdXW5tcmCjDq/TujRsrJ5COIQyidDZOjvn+FJtIw5sr4aY0dCMYZ8JZ2zop3ZSkuimdm25KhW6OA1aW6qZ8bropF7o5DlhFqpvKuemmUujmOGBVqW6q56abaqGb44DVpLqpnZtuaoVujgNWl+qmfm66qRe6OQ5YQ6qbxrnppvG1dDPy67paiFp0vh+pgdGL9epyNhhtAuVjx0fIXHCXZWV3GFFgIUiUtrn+YAcwrxBctgh1YPyLJ9iGW4ZlCbCsWJu2kQn/ckPRrdXroUqam6//ovwQFcBF5T5OAuwT/k4e67cakrHbWf3C7Qkdgs33JFwJNvlZX3Zuwhn767+XY/+IJSLZGFu9oE7UmCcgDCaEBAhuMpp1vUrA7/B4pYTHKyc8XiXh8aoJj1dLeLx6wuM11JEwa0tmnb1lhkzCTnN5h7qofQ/bZrY+42ntXl6VF19eGDeVRUpO83M8Wmwadlr2KiX5KV9LJfItM1EW8vc0kvC33sB9NQSSl37ym6xQLZDpDTctQId7EGUXW8GQ3eIgXzDcg/zAeJkE7x0RoHRhFXqISXqJlRYAwUg0/l0PSIku9rKIrJRHZOUsIivnEVkli8gqeURWzSKyah6R1bKIrJZHZPUsIqvnEVkji8gah0UW+4gj+znSCTyhRX6ftGOpK5RtFmvdmPrSYrGbCZlTWO1GIhwtFv8AbcH5beo8AAA="}]}]'
    http_version: 
  recorded_at: Wed, 12 Apr 2017 08:02:35 GMT
recorded_with: VCR 3.0.3
