---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:<%= feed_uuid %>,type:r,mtypes:.*\\|Platform_File\\
        Store_Total\\ Space\\|.*"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '140'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 25 Apr 2017 14:35:57 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1643'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.r.platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem","data":[{"timestamp":1493124041955,"value":"H4sIAAAAAAAAAO2bbW/aOhTHv0oUqe96lfIQ0Ir6orejE9IYiNAXE0LINzFttMRGxmFDFfnsswmQOJgAXR64I2+axjE+5/z4H8dxDu+qjRYQUUyWBiWeST0C1ft3lS5n7KgSOMceMaF6q1qAAn5lRvAMEmrDOTtb3aq2xfrNHECnmLi+1uu3B4/DzrcvE+O7MWx3H+4+mU0d1JqN+rQ+6bGPAmqjV2M5p9BlwyLgckNHemGPvmLWsDGJTOzuzrY+DpnLfUDf2Ggabb2Bnz88BxBt2oqOrRHa6m+cDe3cVO82pth45pvtWAQiHqwLKbFN9X70nhx/t+MP/JFg6INIxn536O97qARXJ32CTTifK0/YQzTEF29O4hXEdBotN5HW1hvWsDVsYseBJrUx6iAKyQI46j3yHEfkulrdXgrQ4KA89V+UrxhYIdL9CzlBDQ6caf+F/d0Y/7+C5e4rjwt28RXuwY1dzBswN88OoQOnQh6Hs87xueGDeLXnztf2xBj2Bu0HzYILzQUz1kObQgsT8M8bdiM8n20HKgabxaEyOtB5nNk0yo1zutx88RPoCdxE5YbsJkNMgaMYM2BG2IqNWWg0CjDwgZ9tDF5e4v8J4Zc5+I+fiIhjrZkzDux9APL4OOdsoBKM6cnpzjuX6R6iKNO9KMJlup8A1T+Q2NeYwn6ZrDmwLNPyEL5uu9sbfH/oQheTZYhmd55NPm6GLz4ThfBF+QRtk8cFsJ21TuKMJFeykFDcD6afnb0LzMfjRIM5LE4z1pohye2kdjbFDNOwP+g9tQ2jN3i429vkwkQZ3WV3b9xZuYB0jGAQpbNzcsL3p9hEGt1ciTZloRvBOBPO1tZF6aYi1U3l2nRTKXVzHrCqVDfVa9NNtdTNecBqUt3Urk03tVI35wGrS3VTvzbd1EvdnAdMl+pGvzbd6KVuzgPWkOqmcW26aZS6OQ9YU6qb5rXppvl36WYc1HW1EbXp8jhSE6Op/epxNhjtAuVjJ0fIXPDWZWVPGFFgI0iUjrX9YBcwrxBctwh1YPyLJ9iBe4ZlCbCuWJt3kAV/cUPxrdX7kUpau6//pvocF8BN7XOSBNgngp081m8zJGN3sPqF2xM6hJvvabgSbvKzvuzcggv2N3gvx/4RS0TyMbZ5QZ2qMV9AGE4IKRDcZTTvmoLf0fEqKY9XTXm8Wsrj1VMeT095vEbK4zXVsTBrS2ado2WGTMJua32HutH/jdpmtv7EU/2zvCovubwwaSqLlZwW53i82DTqtOxVSvpTvpZJ5Htm4izk72kk4e+9gfvbEEhe+slvskK1QK433KwAne5BnF1iBUN+i4NiwXAPigPj5xK8f0aA0oVV5CEm7SVWVgAEI/H4Dz0gpbrYyyOyShGRVfOIrFpEZLU8IqsVEVk9j8jqRUSm5xGZXkRkjTwiaxQRWTOPyJqnRZb4iCP7OdIFPKHFfp90YKkrlG2Wa92E+tJysZsLmUtY7cYiHK9WvwGHkfIC6jwAAA=="}]}]'
    http_version: 
  recorded_at: Tue, 25 Apr 2017 14:35:57 GMT
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:<%= feed_uuid %>,type:mt,id:Platform_File%20Store_Total%20Space"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '127'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 25 Apr 2017 14:35:57 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '396'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.mt.Platform_File Store_Total Space","data":[{"timestamp":1493124041389,"value":"H4sIAAAAAAAAAFWPT4vCQAzFv4rk3IPgrbdd/IO3hXYPnmSYxm4gTUrMiCL97s5QFfcU3kvej5c7kFxQXO3WuKXoyRDqO/htzBMGdKPYFlFBFzyU3Wg6ojnhOaupAury5Q8HP6kNxy0xLpoMxGOrHnjRjCGWuIShIP+bmrxXkv5JkqjDWyUhz4HvQ7tp8uncZZ1LtHO5PqS+MKIyY3RS2YujXQJDvVouq9cTu6/f3QYyMP4Rd4ZS8NO8Pu+lwyvUkpirj3c//ekB8Z4mnSUBAAA="}]}]'
    http_version: 
  recorded_at: Tue, 25 Apr 2017 14:35:57 GMT
recorded_with: VCR 3.0.3
