---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:<%= feed_uuid %>,type:r,mtypes:.*\\|Platform_File\\
        Store_Total\\ Space\\|.*"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '140'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 12 Apr 2017 15:07:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1639'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.r.platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem","data":[{"timestamp":1492009340700,"value":"H4sIAAAAAAAAAO2bXW/aPBTHv0oUqXedwjtqUS+6jj5CGg+I0IsJIeQlpo2W2Mg4bKgin302ARIHE6DLCxu5aRrH+Jzz438cxzm8qxZaQEQxWeqUuAZ1CVTv31W6nLGjSuAcu8SA6q1qAgr4lRnBM0ioBefsbHWrWibrN7MBnWLieFqv3x48Djv//zfRv+nDdvcB1O5K5bs7szr93pj02EcBtdCrvpxT6LBhEXC4oSO9sEtfMWvYmEQGdnZnWx+HzOU+oG9sNI223sDPH64NiDZthcfWCG31N84Gdm4qpY0pNp7xZtkmgYgH60BKLEO9H73Hx9/teANvJBj6IJKx1x16+x4q/tVJn2ADzufKE3YRDfBFm+N4+TGdRsuJpbX1hjVsDRvYtqFBLYw6iEKyALZ6j1zbFrmuVreXAtQ/KE/9F+UrBmaAdP9CRlD9A2faf2F/N8b/VrDcfeVxwS6+wj24kYtZA+bm2SFw4FTI42DWOT43fBCv9tz52p7ow96g/aCZcKE5YMZ6aFNoYgI+vWEnxPPZsqGis1kcKqMDncepTaPcOKfLzec/gZ7ATVRuwG4yxBTYij4DRoit2JiGRsMAfR/42cbg5SX+nxB+mYPv/EREHGlNnbFv7wOQx8c5pwOVYExPTnfeuUj3AEWR7nkRLtL9BKjegcS+xhT2imTNgGWRlofwddvd3uDbQxc6mCwDNLvzdPJxM3z+mSiEL8rHb5s8LoBlr3USZSS5koaEon4w/ezsXWA+Hifqz2FRmpHWFEluJ7WzKaaYhv1B76mt673BQ2lvkwsTZVRK7964s3IB6RjCIEpn5+SE70+xiTS8uRJuSkM3gnEmnK2ti9JNWaqb8rXpplzo5jxgFaluKtemm0qhm/OAVaW6qV6bbqqFbs4DVpPqpnZtuqkVujkPWF2qm/q16aZe6OY8YA2pbhrXpptGoZvzgDWlumlem26a/5Zuxn5dVxtRiy6PIzUwmlqvLmeD0S5QPnZ8hMwFd11W9oQRBRaCROmY2w92AfMKwXWLUAfGv3iCbbhnWJYA64q1eQeZ8Bc3FN1avR+ppLX7+m8qz1EB3FS/xEmAfcLfyWP9NkMydgerX7g9oUOw+Z6EK8EmP+vLzk24YH/993LsH7FEJBtjmxfUiRrzBITBhJAAwV1Gs66lBPwOj1dOeLxKwuNVEx6vlvB49YTHayQ8XlMdC7O2ZNY5WmbIJOy01neom/rnsG1m6088rX+RV+XFlxfGTWWRktP8HI8Wm4adlr1KSX7K11KJfM9MlIX8PY0k/L03cP8aAslLP/lNVqgWyPSGmxag0z2IsoutYMhucZAvGO5BfmC8TIL3zghQurAKPcQkvcRKC4BgJBr/oQekRBd7WURWziOyShaRVfKIrJpFZNU8IqtlEVktj8jqWURWzyOyRhaRNfKIrJlFZM3TIot9xJH9HOkCntAiv086sNQVyjaLtW5MfWmx2M2EzCWsdiMRjler3xZEdMXqPAAA"}]}]'
    http_version: 
  recorded_at: Wed, 12 Apr 2017 15:07:47 GMT
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:<%= feed_uuid %>,type:mt,id:Platform_File%20Store_Total%20Space"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '127'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 12 Apr 2017 15:07:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '396'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.mt.Platform_File Store_Total Space","data":[{"timestamp":1492009340021,"value":"H4sIAAAAAAAAAFWPT4vCQAzFv4rk3IPgrbdd/IO3hXYPnmSYxm4gTUrMiCL97s5QFfcU3kvej5c7kFxQXO3WuKXoyRDqO/htzBMGdKPYFlFBFzyU3Wg6ojnhOaupAury5Q8HP6kNxy0xLpoMxGOrHnjRjCGWuIShIP+bmrxXkv5JkqjDWyUhz4HvQ7tp8uncZZ1LtHO5PqS+MKIyY3RS2YujXQJDvVouq9cTu6/f3QYyMP4Rd4ZS8NO8Pu+lwyvUkpirj3c//ekB8Z4mnSUBAAA="}]}]'
    http_version: 
  recorded_at: Wed, 12 Apr 2017 15:07:47 GMT
recorded_with: VCR 3.0.3
