---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/raw/query
    body:
      encoding: UTF-8
      string: '{"fromEarliest":true,"order":"DESC","tags":"module:inventory,feed:03eca767\\-e48f\\-4f0b\\-9a8a\\-d8f46112c9a5,type:rt,id:WildFly%20Server"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '140'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 05 Apr 2017 09:12:20 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1015'
    body:
      encoding: UTF-8
      string: '[{"id":"inventory.<%= feed_uuid %>.rt.WildFly Server","data":[{"timestamp":1491383533788,"value":"H4sIAAAAAAAAAO1WUW/TMBD+K5afXYnnvaBBhyhiBTXrEEITcuPrYsmxg33uqKb9d85x26RdthVUCR54SfzdOfc5d98ld8+1XYFF59cF+lhi9MDP7jmuG7pzD8FFX8JVgoIriTJ5G+8a8KghEHoQXCva+0Ub9c6sWQF+BZ52W1nDkN1FvHXa3m6etaWrN4hgWdF2DzbRJBKJ2tmW/uzb/fMHGENj3Loj3uFjCQm+RKGDXBhgOXRNievRDflOR31hn2Qecp2O+MN41lFlcLrgMzBOqi7+Dh8tkhT+wqLG9csKaaQnGgSfBBV2rDYa8xyj4CtpYtsXUpFx5KxZ97pk4ZxJ3QGh9LpJgk2yrwAr8IwuLLTSZ6Fy0SgWUHpk2jIfrSUKVjsF7Hx8OZl+/zT9+JXdVWCZRkbdl7aGNvZSRoPX+Rx8KU1IDenhR9Qe6N1aC500BhiV0VNycJRpR6WzS307dN6jYlJQ7ww8Tt9hrW+OKXd++SEVD/pOqbQQa9ijy/h0FEUVUbk725H0LP+ooFHXQBt76tBt4vfFfJV3JdEGID2pwNAxaYy7Y7JEvQJGVgtl2t/6lJfaPhbZq0HRboT+UksVuX96HbWAbZOAYnKJbZPllL/+OwovYmjA9r5oneG/Ap5SwCkLMLfqYA7oWY7v9RvxW2XI39iYx5WirKCWf1KLaT5xexP8s3eKRjK2se5Bwa/Bh1yb7Urw2eaPckl/lPSN60PB8wTGCpTYKrMPxVaonXsPCz6fT8Ypm+km+HtX08RBRSzT7Ej2A4Pg0/RX277Qbp2eDLipzG4p+BsXietcUQECJfYACz6p64hpzCFftya7ZW+dRZIazZZn+7CT1VB5hrTVdkCYkGB+5ro9/AL1kx5MIQsAAA=="}]}]'
    http_version: 
  recorded_at: Wed, 05 Apr 2017 09:12:20 GMT
recorded_with: VCR 3.0.3
