---
http_interactions:
- request:
    method: post
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/api/urls
    body:
      encoding: UTF-8
      string: '{"url":"http://bsd.de"}'
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '23'
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 05 Apr 2017 09:12:17 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/hawkular.1.0.0+json
      Content-Length:
      - '44'
    body:
      encoding: UTF-8
      string: Url URL[url='http://bsd.de'] already exists.
    http_version: 
  recorded_at: Wed, 05 Apr 2017 09:12:17 GMT
recorded_with: VCR 3.0.3
