---
http_interactions:
- request:
    method: get
    uri: http://<%= super_secret_username %>:<%= super_secret_password %>@localhost:8080/hawkular/metrics/strings/tags/module:inventory,feed:*
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 05 Apr 2017 09:12:16 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '72'
    body:
      encoding: UTF-8
      string: '{"feed":["03eca767-e48f-4f0b-9a8a-d8f46112c9a5"],"module":["inventory"]}'
    http_version: 
  recorded_at: Wed, 05 Apr 2017 09:12:16 GMT
recorded_with: VCR 3.0.3
